/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.codingstyle.live.commission.commission;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
